// react-typescript/src/pages/Login/index.tsx
import React from "react";
import { connect } from "react-redux"
import { Button, Input, Form } from 'react-vant'
import { useNavigate } from "react-router-dom"

import { add, query } from "../../action/userAction"
import Header from "./header";
import { Usequery } from "../../server/userServer"

function Login(props: any) {
    const [form] = Form.useForm();
    const history = useNavigate() //react-router-dom6版本函数组件路由跳转
    const onFinish =  (values: Object) => {
      
        // history('/home')
    }

    return (
        <div className={'login'}>
            <Header />
            <Form
                form={form}
                onFinish={onFinish}
                footer={
                    <div style={{ margin: '16px 16px 0', display: "flex" }}>
                        <Button round nativeType='submit' type='primary' block>
                            登录
                        </Button>
                        <Button round block>
                            注册
                        </Button>
                    </div>
                }
            >
                <Form.Item
                    rules={[{
                        required: true,
                        message: '请填输入4到16为包含数字和大小写字母以字母开头用户名',
                        pattern: /^[a-zA-Z][a-zA-Z0-9]{3,15}$/
                    }]}
                    name='username'
                    label='用户名'
                >
                    <Input placeholder='请输入用户名' />
                </Form.Item>
                <Form.Item
                    rules={[{ required: true, message: '请填写6到10位的密码', pattern: /^[a-zA-Z0-9]{6,10}$/ }]}
                    name='password'
                    label='密码'
                >
                    <Input type="password" placeholder='请输入密码' />
                </Form.Item>
            </Form>
        </div>
    )
}

const mapStateToProps = (state: any) => ({ ...state })

const mapDispatchToProps = {
    add, query
}

export default connect(mapStateToProps, mapDispatchToProps)(Login);

// vite-vue3-typescript/src/pages/Login/Login.vue
<template>
    <div class="login">
        <van-form @submit="onSubmit">
            <van-cell-group inset>
                <van-field
                        v-model="username"
                        name="username"
                        label="用户名"
                        placeholder="用户名"
                        :rules="[{ required: true, message: '请填写用户名' }]"
                />
                <van-field
                        v-model="password"
                        type="password"
                        name="password"
                        label="密码"
                        placeholder="密码"
                        :rules="[{ required: true, message: '请填写密码' }]"
                />
            </van-cell-group>
            <div style="margin: 16px;">
                <van-button round block type="primary" native-type="submit">
                    登录
                </van-button>
            </div>
        </van-form>


    </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import userServe from "@/server/userServe";
const username = ref('');
const password = ref('');
const onSubmit = async (values:Object) => {

    const res:any=await userServe.query(values);
    if(res.code===0){
        alert('登录成功')
    }

};

</script>
